server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cyclone111/config-server
          clone-on-startup: true