server:
  port: 8081


spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: configserver:http://localhost:8085/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/

#Resilience config
management:
  health:
    circuitbreakers:
      enable: true
  endpoints:
    web:
      exposure:
        include: health
  endpont:
    health:
      enabled: true
      show-details: true

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelCircuitMethod:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED